### ISSUE TITLE
Request to have my username removed from the code

### ISSUE THREAD

**Issue by MDMCK10** [thee666/RETARDBOT#1]
Hello,

It has recently come to my attention that [line 34 of retardbot.js](https://github.com/thee666/RETARDBOT/blob/main/retardbot.js#L34) contains references to part of my username in the form of `MDMCKBOT_` and `EGGBOT_`.

I am requesting that these references be removed from the relevant files in a timely manner.

Thank you for your cooperation.

**Comment by thee666** [comment]
OK

**Comment by marcii-101** [comment]
You forgot to remove the name from 34!
